package main

var routes = Routes{
  Route{
    "CurrenciesIndex",
    "GET",
    "/currencies",
    CurrenciesIndex,
  },
  Route{
    "CurrencyShow",
    "GET",
    "/currencies/{code}",
    CurrencyShow,
  },
  Route{
    "CurrencyGetNewAddress",
    "POST",
    "/currencies/{code}/getnewaddress",
    CurrencyGetNewAddress,
  },
  Route{
    "CurrencyGetBalance",
    "POST",
    "/currencies/{code}/getbalance",
    CurrencyGetBalance,
  },
  Route{
    "CurrencySendToAddress",
    "POST",
    "/currencies/{code}/sendtoaddress",
    CurrencySendToAddress,
  },
  Route{
    "UserProfile",
    "POST",
    "/auth/login",
    AuthCreate,
  },
}